"""loan status change

Revision ID: 14c4afc60447
Revises: 298fe44c6817
Create Date: 2025-08-18 12:49:55.040434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c4afc60447'
down_revision: Union[str, Sequence[str], None] = '298fe44c6817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE loanstatus ADD VALUE IF NOT EXISTS 'COMPLETED'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
