"""Changed emi_schedule_date to str from date

Revision ID: 1cb43c880744
Revises: 7f3fe31905e5
Create Date: 2025-08-11 15:46:29.707384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb43c880744'
down_revision: Union[str, Sequence[str], None] = '7f3fe31905e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emi_schedule_date', 'emi_schedule_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emi_schedule_date', 'emi_schedule_date',
               existing_type=sa.String(length=500),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
