"""added billing_start


Revision ID: 20c1db0ae8a3
Revises: 413ee89ebacb
Create Date: 2025-08-25 12:57:45.692046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c1db0ae8a3'
down_revision: Union[str, Sequence[str], None] = '413ee89ebacb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('billing_start', sa.BigInteger(), nullable=True))
    op.add_column('prepayment', sa.Column('billing_start', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prepayment', 'billing_start')
    op.drop_column('invoices', 'billing_start')
    # ### end Alembic commands ###
