"""added loan disbursement detial table

Revision ID: 24d223655beb
Revises: 40481f51ec19
Create Date: 2025-08-05 16:38:50.152679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24d223655beb'
down_revision: Union[str, Sequence[str], None] = '40481f51ec19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_disbursement_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.Enum('BANK_TRANSFER', 'CASH', 'CHEQUE', 'UPI', name='paymenttype'), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('transferred_amount', sa.Float(), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('account_holder_name', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('ifsc_code', sa.String(), nullable=True),
    sa.Column('payment_file', sa.String(length=500), nullable=True),
    sa.Column('cheque_number', sa.String(), nullable=True),
    sa.Column('upi_id', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['loan_applicants.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_disbursement_detail_applicant_id'), 'loan_disbursement_detail', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_loan_disbursement_detail_id'), 'loan_disbursement_detail', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_disbursement_detail_id'), table_name='loan_disbursement_detail')
    op.drop_index(op.f('ix_loan_disbursement_detail_applicant_id'), table_name='loan_disbursement_detail')
    op.drop_table('loan_disbursement_detail')
    # ### end Alembic commands ###
