"""Modify Processing Fee and  Bank Account Model

Revision ID: 314899f4e5ad
Revises: 7a317096e342
Create Date: 2025-07-29 15:10:56.741823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '314899f4e5ad'
down_revision: Union[str, Sequence[str], None] = '7a317096e342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_accounts', sa.Column('client_id', sa.String(), nullable=True))
    op.add_column('bank_accounts', sa.Column('bank_name', sa.String(), nullable=False))
    op.create_index(op.f('ix_bank_accounts_account_number'), 'bank_accounts', ['account_number'], unique=False)
    op.create_index(op.f('ix_bank_accounts_bank_name'), 'bank_accounts', ['bank_name'], unique=False)
    op.create_index(op.f('ix_bank_accounts_client_id'), 'bank_accounts', ['client_id'], unique=False)
    op.add_column('processing_fees', sa.Column('label', sa.String(), nullable=False))
    op.add_column('processing_fees', sa.Column('min_score', sa.Integer(), nullable=True))
    op.add_column('processing_fees', sa.Column('max_score', sa.Integer(), nullable=True))
    op.add_column('processing_fees', sa.Column('min_fee_percent', sa.Float(), nullable=False))
    op.add_column('processing_fees', sa.Column('max_fee_percent', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_processing_fee_amount'), table_name='processing_fees')
    op.drop_index(op.f('ix_processing_fee_rate_percent'), table_name='processing_fees')
    op.drop_constraint(op.f('uq_processing_fee_rate_amount'), 'processing_fees', type_='unique')
    op.create_index('ix_proc_fee_max_score', 'processing_fees', ['max_score'], unique=False)
    op.create_index('ix_proc_fee_min_score', 'processing_fees', ['min_score'], unique=False)
    op.create_unique_constraint('uq_proc_fee_score_loan', 'processing_fees', ['min_score', 'max_score'])
    op.drop_column('processing_fees', 'rate_percent')
    op.drop_column('processing_fees', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_fees', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('processing_fees', sa.Column('rate_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint('uq_proc_fee_score_loan', 'processing_fees', type_='unique')
    op.drop_index('ix_proc_fee_min_score', table_name='processing_fees')
    op.drop_index('ix_proc_fee_max_score', table_name='processing_fees')
    op.create_unique_constraint(op.f('uq_processing_fee_rate_amount'), 'processing_fees', ['rate_percent', 'amount'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_processing_fee_rate_percent'), 'processing_fees', ['rate_percent'], unique=False)
    op.create_index(op.f('ix_processing_fee_amount'), 'processing_fees', ['amount'], unique=False)
    op.drop_column('processing_fees', 'max_fee_percent')
    op.drop_column('processing_fees', 'min_fee_percent')
    op.drop_column('processing_fees', 'max_score')
    op.drop_column('processing_fees', 'min_score')
    op.drop_column('processing_fees', 'label')
    op.drop_index(op.f('ix_bank_accounts_client_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_bank_name'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_account_number'), table_name='bank_accounts')
    op.drop_column('bank_accounts', 'bank_name')
    op.drop_column('bank_accounts', 'client_id')
    # ### end Alembic commands ###
