"""1_Created Loan Approval Document model

Revision ID: 35300dda060c
Revises: 1cb43c880744
Create Date: 2025-08-12 15:13:34.165267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35300dda060c'
down_revision: Union[str, Sequence[str], None] = '1cb43c880744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approved_loan_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.Text(), nullable=True),
    sa.Column('document_file', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['loan_applicants.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approved_loan_documents_applicant_id'), 'approved_loan_documents', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_approved_loan_documents_id'), 'approved_loan_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approved_loan_documents_id'), table_name='approved_loan_documents')
    op.drop_index(op.f('ix_approved_loan_documents_applicant_id'), table_name='approved_loan_documents')
    op.drop_table('approved_loan_documents')
    # ### end Alembic commands ###
