"""Added Custom Interest Rate Percentage

Revision ID: 356e1d6e90fe
Revises: 9ea085ce4a08
Create Date: 2025-07-25 14:15:00.096429

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '356e1d6e90fe'
down_revision: Union[str, Sequence[str], None] = '9ea085ce4a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Drop default (to prevent casting issue)
    op.execute(
        """
        ALTER TABLE credit_score_range_rate
            ALTER COLUMN loan_type DROP DEFAULT
        """
    )

    # Step 2: Convert to ENUM using explicit casting
    op.execute(
        """
        ALTER TABLE credit_score_range_rate
        ALTER
        COLUMN loan_type TYPE loantype
            USING loan_type::loantype
        """
    )

    # Step 3: Set default back as ENUM
    op.execute(
        """
        ALTER TABLE credit_score_range_rate
            ALTER COLUMN loan_type SET DEFAULT 'PERSONAL'
        """
    )
    op.add_column('loan_applicants', sa.Column('credit_score_range_rate_id', sa.Integer(), nullable=True))
    op.add_column('loan_applicants', sa.Column('custom_rate_percentage', sa.Float(), nullable=True))
    op.create_foreign_key(
        None, 'loan_applicants', 'credit_score_range_rate', ['credit_score_range_rate_id'], ['id'], ondelete='SET NULL'
    )
    op.add_column('loan_approval_details', sa.Column('final_interest_rate', sa.Float(), nullable=False))
    op.add_column('loan_approval_details', sa.Column('custom_interest_rate', sa.Float(), nullable=True))
    op.alter_column(
        'loan_approval_details', 'interest_rate_id',
        existing_type=sa.INTEGER(),
        nullable=True
    )
    op.alter_column(
        'loan_approval_details', 'disbursed_amount',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.alter_column(
        'loan_approval_details', 'disbursed_amount',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False
    )
    op.alter_column(
        'loan_approval_details', 'interest_rate_id',
        existing_type=sa.INTEGER(),
        nullable=False
    )
    op.drop_column('loan_approval_details', 'custom_interest_rate')
    op.drop_column('loan_approval_details', 'final_interest_rate')
    op.drop_constraint(None, 'loan_applicants', type_='foreignkey')
    op.drop_column('loan_applicants', 'custom_rate_percentage')
    op.drop_column('loan_applicants', 'credit_score_range_rate_id')
    op.alter_column(
        'credit_score_range_rate', 'loan_type',
        existing_type=sa.Enum('PERSONAL', 'LAP', 'MSME', 'MICRO', name='loantype'),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        existing_server_default=sa.text("'PERSONAL'::character varying")
    )
    # ### end Alembic commands ###
