"""Added Interest Rate and Processing Fee in Loan Model

Revision ID: 3d15a4239597
Revises: 314899f4e5ad
Create Date: 2025-07-30 11:03:21.621410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d15a4239597'
down_revision: Union[str, Sequence[str], None] = '314899f4e5ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_applicants', sa.Column('credit_score_range_rate_percentage', sa.Float(), nullable=True))
    op.add_column('loan_applicants', sa.Column('processing_fee_id', sa.Integer(), nullable=True))
    op.add_column('loan_applicants', sa.Column('processing_fee', sa.Float(), nullable=True))
    op.add_column('loan_applicants', sa.Column('custom_processing_fee', sa.Float(), nullable=True))
    op.add_column('loan_applicants', sa.Column('tenure_months', sa.Integer(), nullable=True))
    op.create_foreign_key("loan_applicants_processing_fee_id_fkey", 'loan_applicants', 'processing_fees', ['processing_fee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("loan_applicants_processing_fee_id_fkey", 'loan_applicants', type_='foreignkey')
    op.drop_column('loan_applicants', 'tenure_months')
    op.drop_column('loan_applicants', 'custom_processing_fee')
    op.drop_column('loan_applicants', 'processing_fee')
    op.drop_column('loan_applicants', 'processing_fee_id')
    op.drop_column('loan_applicants', 'credit_score_range_rate_percentage')
    # ### end Alembic commands ###
