"""added consent and disbursement field in loan application table

Revision ID: 40481f51ec19
Revises: 90c43bbd0f4b
Create Date: 2025-08-05 13:08:24.056814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40481f51ec19'
down_revision: Union[str, Sequence[str], None] = '90c43bbd0f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_applicants', sa.Column('loan_acceptance_agreement_consent', sa.Boolean(), nullable=True))
    op.add_column('loan_applicants', sa.Column('loan_insurance_agreement_consent', sa.Boolean(), nullable=True))
    op.add_column('loan_applicants', sa.Column('loan_policy_and_assignment_consent', sa.Boolean(), nullable=True))
    op.add_column('loan_applicants', sa.Column('available_for_disbursement', sa.Boolean(), nullable=True))
    op.add_column('loan_applicants', sa.Column('disbursement_apply_date', sa.DateTime(), nullable=True))
    op.add_column('loan_applicants', sa.Column('is_disbursement_manual', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_applicants', 'is_disbursement_manual')
    op.drop_column('loan_applicants', 'disbursement_apply_date')
    op.drop_column('loan_applicants', 'available_for_disbursement')
    op.drop_column('loan_applicants', 'loan_policy_and_assignment_consent')
    op.drop_column('loan_applicants', 'loan_insurance_agreement_consent')
    op.drop_column('loan_applicants', 'loan_acceptance_agreement_consent')
    # ### end Alembic commands ###
