"""added due_payment flag invoiceType

Revision ID: 413ee89ebacb
Revises: e4502de88c81
Create Date: 2025-08-23 18:21:40.176912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '413ee89ebacb'
down_revision: Union[str, Sequence[str], None] = 'e4502de88c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE invoicetype ADD VALUE IF NOT EXISTS 'DUE_PAYMENT'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
