"""Modify Loan Approved Details

Revision ID: 455b8ed70d8f
Revises: 46e61aceb5bc
Create Date: 2025-07-30 16:13:09.394950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '455b8ed70d8f'
down_revision: Union[str, Sequence[str], None] = '46e61aceb5bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
