"""Modify Loan Approved Details

Revision ID: 46e61aceb5bc
Revises: 3d15a4239597
Create Date: 2025-07-30 13:54:29.755076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e61aceb5bc'
down_revision: Union[str, Sequence[str], None] = '3d15a4239597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_approval_details', sa.Column('approved_interest_rate', sa.Float(), nullable=False))
    op.add_column('loan_approval_details', sa.Column('approved_processing_fee', sa.Float(), nullable=False))
    op.add_column('loan_approval_details', sa.Column('custom_processing_fee', sa.Float(), nullable=True))
    op.add_column('loan_approval_details', sa.Column('approved_tenure_months', sa.Integer(), nullable=False))
    op.add_column('loan_approval_details', sa.Column('final_tenure_months', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_approval_interest_rate_id'), table_name='loan_approval_details')
    op.drop_index(op.f('ix_approval_processing_fee_id'), table_name='loan_approval_details')
    op.drop_constraint(op.f('loan_approval_details_processing_fee_id_fkey'), 'loan_approval_details', type_='foreignkey')
    op.drop_constraint(op.f('loan_approval_details_interest_rate_id_fkey'), 'loan_approval_details', type_='foreignkey')
    op.drop_column('loan_approval_details', 'processing_fee_id')
    op.drop_column('loan_approval_details', 'interest_rate_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_approval_details', sa.Column('interest_rate_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('loan_approval_details', sa.Column('processing_fee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('loan_approval_details_interest_rate_id_fkey'), 'loan_approval_details', 'credit_score_range_rate', ['interest_rate_id'], ['id'])
    op.create_foreign_key(op.f('loan_approval_details_processing_fee_id_fkey'), 'loan_approval_details', 'processing_fees', ['processing_fee_id'], ['id'])
    op.create_index(op.f('ix_approval_processing_fee_id'), 'loan_approval_details', ['processing_fee_id'], unique=False)
    op.create_index(op.f('ix_approval_interest_rate_id'), 'loan_approval_details', ['interest_rate_id'], unique=False)
    op.drop_column('loan_approval_details', 'final_tenure_months')
    op.drop_column('loan_approval_details', 'approved_tenure_months')
    op.drop_column('loan_approval_details', 'custom_processing_fee')
    op.drop_column('loan_approval_details', 'approved_processing_fee')
    op.drop_column('loan_approval_details', 'approved_interest_rate')
    # ### end Alembic commands ###
