"""temporary removed constraint from bank account table

Revision ID: 49c9ac34c786
Revises: 4fc880c3baa6
Create Date: 2025-08-02 13:02:57.029108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c9ac34c786'
down_revision: Union[str, Sequence[str], None] = '4fc880c3baa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_account_number_ifsc'), 'bank_accounts', type_='unique')
    op.drop_constraint(op.f('uq_loan_type'), 'bank_accounts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_loan_type'), 'bank_accounts', ['applicant_id', 'type'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_account_number_ifsc'), 'bank_accounts', ['account_number', 'ifsc_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
