"""Added is_verified field in LoanDocument Model

Revision ID: 4fc880c3baa6
Revises: 455b8ed70d8f
Create Date: 2025-07-31 15:29:10.398072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc880c3baa6'
down_revision: Union[str, Sequence[str], None] = '455b8ed70d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_documents', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_documents', 'is_verified')
    # ### end Alembic commands ###
