"""Created User Cibil Reports

Revision ID: 5557978f731e
Revises: b686585a7c0b
Create Date: 2025-07-18 13:28:45.091900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5557978f731e'
down_revision: Union[str, Sequence[str], None] = 'b686585a7c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cibil_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('pan_number', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('credit_score', sa.String(), nullable=True),
    sa.Column('credit_report', sa.JSON(), nullable=True),
    sa.Column('report_refresh_date', sa.Date(), nullable=True),
    sa.Column('next_eligible_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_cibil_reports_client_id'), 'user_cibil_reports', ['client_id'], unique=False)
    op.create_index(op.f('ix_user_cibil_reports_credit_score'), 'user_cibil_reports', ['credit_score'], unique=False)
    op.create_index(op.f('ix_user_cibil_reports_id'), 'user_cibil_reports', ['id'], unique=False)
    op.create_index(op.f('ix_user_cibil_reports_mobile'), 'user_cibil_reports', ['mobile'], unique=False)
    op.create_index(op.f('ix_user_cibil_reports_next_eligible_date'), 'user_cibil_reports', ['next_eligible_date'], unique=False)
    op.create_index(op.f('ix_user_cibil_reports_pan_number'), 'user_cibil_reports', ['pan_number'], unique=False)
    op.create_index(op.f('ix_user_cibil_reports_report_refresh_date'), 'user_cibil_reports', ['report_refresh_date'], unique=False)
    op.create_index(op.f('ix_user_cibil_reports_user_id'), 'user_cibil_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_cibil_reports_user_id'), table_name='user_cibil_reports')
    op.drop_index(op.f('ix_user_cibil_reports_report_refresh_date'), table_name='user_cibil_reports')
    op.drop_index(op.f('ix_user_cibil_reports_pan_number'), table_name='user_cibil_reports')
    op.drop_index(op.f('ix_user_cibil_reports_next_eligible_date'), table_name='user_cibil_reports')
    op.drop_index(op.f('ix_user_cibil_reports_mobile'), table_name='user_cibil_reports')
    op.drop_index(op.f('ix_user_cibil_reports_id'), table_name='user_cibil_reports')
    op.drop_index(op.f('ix_user_cibil_reports_credit_score'), table_name='user_cibil_reports')
    op.drop_index(op.f('ix_user_cibil_reports_client_id'), table_name='user_cibil_reports')
    op.drop_table('user_cibil_reports')
    # ### end Alembic commands ###
