"""added Emi Stepper

Revision ID: 63d32a063c9a
Revises: 8f0ffa58c0f4
Create Date: 2025-08-20 14:23:50.843919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d32a063c9a'
down_revision: Union[str, Sequence[str], None] = '8f0ffa58c0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prepayment', sa.Column('emi_stepper', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prepayment', 'emi_stepper')
    # ### end Alembic commands ###
