"""Initital Migrations

Revision ID: 63d49fc3c16e
Revises: 
Create Date: 2025-07-09 11:24:46.804205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d49fc3c16e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('loan_applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_uid', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('annual_income', sa.Float(), nullable=False),
    sa.Column('desired_loan', sa.Float(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='genderenum'), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_address', sa.String(length=500), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('purpose_of_loan', sa.String(length=500), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('loan_type', sa.Enum('PERSONAL', 'LAP', 'MSME', 'MICRO', name='loantype'), server_default='PERSONAL', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'ON_HOLD', 'APPROVED', 'REJECTED', 'DISBURSED', 'CLOSED', 'CANCELLED', name='loanstatus'), server_default='PENDING', nullable=False),
    sa.Column('approved_loan', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_applicants_email'), 'loan_applicants', ['email'], unique=False)
    op.create_index(op.f('ix_loan_applicants_id'), 'loan_applicants', ['id'], unique=False)
    op.create_index(op.f('ix_loan_applicants_loan_uid'), 'loan_applicants', ['loan_uid'], unique=True)
    op.create_index(op.f('ix_loan_applicants_name'), 'loan_applicants', ['name'], unique=False)
    op.create_index(op.f('ix_loan_applicants_phone_number'), 'loan_applicants', ['phone_number'], unique=False)
    op.create_table('user_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('PAN', 'AADHAR', 'PASSPORT', 'VOTER_ID', 'DRIVING_LICENSE', name='documenttype'), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('document_file', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'document_type', name='_user_doc_uc')
    )
    op.create_index(op.f('ix_user_documents_document_number'), 'user_documents', ['document_number'], unique=False)
    op.create_index(op.f('ix_user_documents_document_type'), 'user_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_user_documents_id'), 'user_documents', ['id'], unique=False)
    op.create_index(op.f('ix_user_documents_user_id'), 'user_documents', ['user_id'], unique=False)
    op.create_table('loan_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('proof_type', sa.Enum('SALARIED', 'SELF_EMPLOYED', name='incomeprooftype'), nullable=True),
    sa.Column('document_type', sa.Enum('PAN', 'AADHAR', 'PASSPORT', 'VOTER_ID', 'DRIVING_LICENSE', name='documenttype'), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('document_file', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', 'CANCELLED', 'UNDER_REVIEW', 'ON_HOLD', name='documentstatus'), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['loan_applicants.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_documents_applicant_id'), 'loan_documents', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_loan_documents_document_number'), 'loan_documents', ['document_number'], unique=False)
    op.create_index(op.f('ix_loan_documents_document_type'), 'loan_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_loan_documents_id'), 'loan_documents', ['id'], unique=False)
    op.create_index(op.f('ix_loan_documents_proof_type'), 'loan_documents', ['proof_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_documents_proof_type'), table_name='loan_documents')
    op.drop_index(op.f('ix_loan_documents_id'), table_name='loan_documents')
    op.drop_index(op.f('ix_loan_documents_document_type'), table_name='loan_documents')
    op.drop_index(op.f('ix_loan_documents_document_number'), table_name='loan_documents')
    op.drop_index(op.f('ix_loan_documents_applicant_id'), table_name='loan_documents')
    op.drop_table('loan_documents')
    op.drop_index(op.f('ix_user_documents_user_id'), table_name='user_documents')
    op.drop_index(op.f('ix_user_documents_id'), table_name='user_documents')
    op.drop_index(op.f('ix_user_documents_document_type'), table_name='user_documents')
    op.drop_index(op.f('ix_user_documents_document_number'), table_name='user_documents')
    op.drop_table('user_documents')
    op.drop_index(op.f('ix_loan_applicants_phone_number'), table_name='loan_applicants')
    op.drop_index(op.f('ix_loan_applicants_name'), table_name='loan_applicants')
    op.drop_index(op.f('ix_loan_applicants_loan_uid'), table_name='loan_applicants')
    op.drop_index(op.f('ix_loan_applicants_id'), table_name='loan_applicants')
    op.drop_index(op.f('ix_loan_applicants_email'), table_name='loan_applicants')
    op.drop_table('loan_applicants')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
