"""Added Name in User Cibil Report model

Revision ID: 7a317096e342
Revises: 87dbaf47b4fe
Create Date: 2025-07-29 10:19:10.324360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a317096e342'
down_revision: Union[str, Sequence[str], None] = '87dbaf47b4fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_cibil_reports', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_cibil_reports_name'), 'user_cibil_reports', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_cibil_reports_name'), table_name='user_cibil_reports')
    op.drop_column('user_cibil_reports', 'name')
    # ### end Alembic commands ###
