"""chaged payment method to optional

Revision ID: 7a7efa9baca2
Revises: 88cfea5afb9e
Create Date: 2025-08-12 16:18:56.933553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a7efa9baca2'
down_revision: Union[str, Sequence[str], None] = '88cfea5afb9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_details', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_details', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
