"""added new option in loanstatus

Revision ID: 7c4e03cea6e5
Revises: c4faae958bda
Create Date: 2025-08-04 10:50:42.476439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c4e03cea6e5'
down_revision: Union[str, Sequence[str], None] = 'c4faae958bda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE loanstatus ADD VALUE IF NOT EXISTS 'USER_ACCEPTED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
