"""added pan_verified and aadhaar_verified field

Revision ID: 8170c7077e39
Revises: 24d223655beb
Create Date: 2025-08-05 18:49:53.589530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8170c7077e39'
down_revision: Union[str, Sequence[str], None] = '24d223655beb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_applicants', sa.Column('pan_verified', sa.Boolean(), nullable=True))
    op.add_column('loan_applicants', sa.Column('aadhaar_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_applicants', 'aadhaar_verified')
    op.drop_column('loan_applicants', 'pan_verified')
    # ### end Alembic commands ###
