"""Added Credit Score in Loan Model

Revision ID: 87dbaf47b4fe
Revises: e0c5b1c0eea4
Create Date: 2025-07-28 17:01:39.159030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87dbaf47b4fe'
down_revision: Union[str, Sequence[str], None] = 'e0c5b1c0eea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_applicants', sa.Column('credit_score', sa.String(), nullable=True))
    op.create_index(op.f('ix_loan_applicants_credit_score'), 'loan_applicants', ['credit_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_applicants_credit_score'), table_name='loan_applicants')
    op.drop_column('loan_applicants', 'credit_score')
    # ### end Alembic commands ###
