"""Added PrePayment Models

Revision ID: 8f0ffa58c0f4
Revises: 14c4afc60447
Create Date: 2025-08-20 13:05:14.285086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f0ffa58c0f4'
down_revision: Union[str, Sequence[str], None] = '14c4afc60447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prepayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='prepayment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prepayment_id'), 'prepayment', ['id'], unique=False)
    op.add_column('payment_details', sa.Column('prepayment_id', sa.Integer(), nullable=True))
    op.alter_column('payment_details', 'foreclosure_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'payment_details', 'prepayment', ['prepayment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_details', type_='foreignkey')
    op.alter_column('payment_details', 'foreclosure_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('payment_details', 'prepayment_id')
    op.drop_index(op.f('ix_prepayment_id'), table_name='prepayment')
    op.drop_table('prepayment')
    # ### end Alembic commands ###
