"""created emi schedule date table

Revision ID: 90c43bbd0f4b
Revises: 7c4e03cea6e5
Create Date: 2025-08-04 16:26:12.476470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = '90c43bbd0f4b'
down_revision: Union[str, Sequence[str], None] = '7c4e03cea6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    existing_loan_type_enum = ENUM('PERSONAL', 'LAP', 'MSME', 'MICRO', name='loantype', create_type=False)

    op.create_table('emi_schedule_date',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('emi_schedule_loan_type', existing_loan_type_enum, nullable=False),
                    sa.Column('emi_schedule_date', sa.Date(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['created_by'], ['users.id']),
                    sa.ForeignKeyConstraint(['modified_by'], ['users.id']),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_emi_schedule_date_id'), 'emi_schedule_date', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emi_schedule_date_id'), table_name='emi_schedule_date')
    op.drop_table('emi_schedule_date')
    # ### end Alembic commands ###
