"""Credit Utility

Revision ID: a1ffd22a619a
Revises: 5557978f731e
Create Date: 2025-07-24 18:52:42.630700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ffd22a619a'
down_revision: Union[str, Sequence[str], None] = '5557978f731e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_score_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('min_score', 'max_score', name='uq_score_range_min_max')
    )
    op.create_index('ix_credit_score_range_max', 'credit_score_ranges', ['max_score'], unique=False)
    op.create_index('ix_credit_score_range_min', 'credit_score_ranges', ['min_score'], unique=False)
    op.create_index(op.f('ix_credit_score_ranges_id'), 'credit_score_ranges', ['id'], unique=False)
    op.create_table('processing_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_percent', sa.Float(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_percent', 'amount', name='uq_processing_fee_rate_amount')
    )
    op.create_index('ix_processing_fee_amount', 'processing_fees', ['amount'], unique=False)
    op.create_index('ix_processing_fee_rate_percent', 'processing_fees', ['rate_percent'], unique=False)
    op.create_index(op.f('ix_processing_fees_id'), 'processing_fees', ['id'], unique=False)
    op.create_table('interest_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_score_range_id', sa.Integer(), nullable=True),
    sa.Column('rate_percentage', sa.Float(), nullable=False),
    sa.Column('loan_type', sa.String(), server_default='PERSONAL', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['credit_score_range_id'], ['credit_score_ranges.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interest_rates_id'), 'interest_rates', ['id'], unique=False)
    op.create_index('ix_interest_score_range', 'interest_rates', ['credit_score_range_id'], unique=False)
    op.create_table('loan_approval_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('interest_rate_id', sa.Integer(), nullable=False),
    sa.Column('processing_fee_id', sa.Integer(), nullable=False),
    sa.Column('processing_fee_amount', sa.Float(), nullable=False),
    sa.Column('approved_loan_amount', sa.Float(), nullable=False),
    sa.Column('disbursed_amount', sa.Float(), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['loan_applicants.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['interest_rate_id'], ['interest_rates.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['processing_fee_id'], ['processing_fees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('applicant_id', name='uq_approval_applicant')
    )
    op.create_index('ix_approval_interest_rate_id', 'loan_approval_details', ['interest_rate_id'], unique=False)
    op.create_index('ix_approval_processing_fee_id', 'loan_approval_details', ['processing_fee_id'], unique=False)
    op.create_index(op.f('ix_loan_approval_details_applicant_id'), 'loan_approval_details', ['applicant_id'], unique=True)
    op.create_index(op.f('ix_loan_approval_details_id'), 'loan_approval_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_approval_details_id'), table_name='loan_approval_details')
    op.drop_index(op.f('ix_loan_approval_details_applicant_id'), table_name='loan_approval_details')
    op.drop_index('ix_approval_processing_fee_id', table_name='loan_approval_details')
    op.drop_index('ix_approval_interest_rate_id', table_name='loan_approval_details')
    op.drop_table('loan_approval_details')
    op.drop_index('ix_interest_score_range', table_name='interest_rates')
    op.drop_index(op.f('ix_interest_rates_id'), table_name='interest_rates')
    op.drop_table('interest_rates')
    op.drop_index(op.f('ix_processing_fees_id'), table_name='processing_fees')
    op.drop_index('ix_processing_fee_rate_percent', table_name='processing_fees')
    op.drop_index('ix_processing_fee_amount', table_name='processing_fees')
    op.drop_table('processing_fees')
    op.drop_index(op.f('ix_credit_score_ranges_id'), table_name='credit_score_ranges')
    op.drop_index('ix_credit_score_range_min', table_name='credit_score_ranges')
    op.drop_index('ix_credit_score_range_max', table_name='credit_score_ranges')
    op.drop_table('credit_score_ranges')
    # ### end Alembic commands ###
