"""added emi_start_day_atm in loan model

Revision ID: b3899ba0765e
Revises: e59e211d1001
Create Date: 2025-08-21 14:46:06.331397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3899ba0765e'
down_revision: Union[str, Sequence[str], None] = 'e59e211d1001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_applicants', sa.Column('emi_start_day_atm', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_applicants', 'emi_start_day_atm')
    # ### end Alembic commands ###
