"""Added new values to DocumentType enum

Revision ID: b686585a7c0b
Revises: 63d49fc3c16e
Create Date: 2025-07-10 12:16:54.506096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b686585a7c0b'
down_revision: Union[str, Sequence[str], None] = '63d49fc3c16e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'ADDRESS_PROOF'")
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'BANK_STATEMENT'")
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'SALARY_SLIP'")
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'ITR'")
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'FORM_16'")
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'PROPERTY_DOCUMENTS'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
