"""Changed Enum For Subscription

Revision ID: bc822037f8ee
Revises: 3a8feefa2cb2
Create Date: 2025-08-08 12:49:59.020670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc822037f8ee'
down_revision: Union[str, Sequence[str], None] = '3a8feefa2cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE subscriptionstatus ADD VALUE IF NOT EXISTS 'AUTHENTICATED'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
