"""added gender field in user cibil report

Revision ID: c4faae958bda
Revises: 2aba3c4653d1
Create Date: 2025-08-02 16:52:42.125376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4faae958bda'
down_revision: Union[str, Sequence[str], None] = '2aba3c4653d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_cibil_reports', sa.Column('gender', sa.Enum('male', 'female', 'other', name='genderenum'), server_default='male', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_cibil_reports', 'gender')
    # ### end Alembic commands ###
