"""changed subscriptionstatus paused

Revision ID: d0991fcc6155
Revises: 6974bbafb73e
Create Date: 2025-08-21 16:29:30.373920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0991fcc6155'
down_revision: Union[str, Sequence[str], None] = '6974bbafb73e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add PAUSED
    op.execute("ALTER TYPE subscriptionstatus ADD VALUE IF NOT EXISTS 'PAUSED'")
    # Add RESUMED
    op.execute("ALTER TYPE subscriptionstatus ADD VALUE IF NOT EXISTS 'RESUMED'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
