""" added is_due_payment flag in pre_payment model

Revision ID: e4502de88c81
Revises: 5819170ae8d4
Create Date: 2025-08-23 17:44:44.450683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4502de88c81'
down_revision: Union[str, Sequence[str], None] = '5819170ae8d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prepayment', sa.Column('is_due_payment', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prepayment', 'is_due_payment')
    # ### end Alembic commands ###
