"""added new status for migration

Revision ID: e59e211d1001
Revises: 14c4afc60447
Create Date: 2025-08-20 16:47:04.132327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from common.enums import LoanStatus

# revision identifiers, used by Alembic.
revision: str = 'e59e211d1001'
down_revision: Union[str, Sequence[str], None] = '14c4afc60447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE loanstatus ADD VALUE IF NOT EXISTS 'APPLICATION_SUBMITTED';")
    op.execute("ALTER TYPE loanstatus ADD VALUE IF NOT EXISTS 'AADHAR_VERIFIED';")
    op.execute("ALTER TYPE loanstatus ADD VALUE IF NOT EXISTS 'DISBURSEMENT_APPROVAL_PENDING';")
    op.execute("ALTER TYPE loanstatus ADD VALUE IF NOT EXISTS 'DISBURSEMENT_APPROVED';")
    op.execute("ALTER TYPE loanstatus ADD VALUE IF NOT EXISTS 'BANK_VERIFIED';")
    op.execute("ALTER TYPE loanstatus ADD VALUE IF NOT EXISTS 'E_MANDATE_GENERATED';")
    op.execute("COMMIT;")

    op.alter_column(
        "loan_applicants",
        "status",
        existing_type=sa.Enum(LoanStatus, name="loanstatus"),
        server_default=LoanStatus.APPLICATION_SUBMITTED.value,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
