"""added order_id in PaymentDetails

Revision ID: ec754002a6c9
Revises: 7a7efa9baca2
Create Date: 2025-08-12 19:04:10.645328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec754002a6c9'
down_revision: Union[str, Sequence[str], None] = '7a7efa9baca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_details', sa.Column('order_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_details', 'order_id')
    # ### end Alembic commands ###
